### ISSUE TITLE
Get error in Chrome - L.MigrationLayer is not a constructor

### ISSUE THREAD

**Issue by wesleyarthur** [lukemonahan/missile_map#2]
Great app. When using this in a splunk dashboard with other panels, I get the following error in Google Chrome:  (It also seems to prevent firefox from loading it intermittently too).

`Uncaught TypeError: L.MigrationLayer is not a constructor
  at new L.migrationLayer (visualization.js:25564)
`

I also get an error about layers-2x.png not being found. It looks like this is defined in visualization.css for some reason but it doesn't exist.  Will try and help out where I can.

**Comment by chaugan** [comment]
I have the same problem. The viz does not like to be on a dashboard with other panels. 

I.e tested with the Maps+ viz on the same dashboard.

**Comment by lukemonahan** [comment]
(Belatedly) fixed in 1.5.0.
